language: node_js
node_js:
  - lts/*
cache:
  directiries:
    - node_modules
install:
  - yarn install
script:
  - yarn build:github
deploy:
  provide: pages
  skip_cleanup: true
  local_dir: dist
  # 在 Github 上生成的 token，允许 Travis 推送代码到你的仓库。
  # 在仓库的 Travis 设置页面，设为安全的环境变量
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main
